"""tests/test_intel_report_pdf.py — INTEL-REPORT-001: Raio-X do Concorrente PDF tests.

Tests:
  1. Full data → valid PDF (non-empty BytesIO, %PDF magic bytes)
  2. LLM failure fallback → PDF still generated (narrative from deterministic fallback)
  3. Empty data dict → ValueError raised
  4. generate_cnpj_narrative deterministic fallback → returns expected keys
"""

from __future__ import annotations

import pytest
from io import BytesIO
from unittest.mock import MagicMock, patch


# ---------------------------------------------------------------------------
# Shared fixtures
# ---------------------------------------------------------------------------

MINIMAL_DATA = {
    "cnpj": "12.345.678/0001-99",
    "fornecedor_nome": "Empresa Teste LTDA",
    "periodo_analisado": "2025-01 a 2025-12",
    "total_contratos": 5,
    "valor_total": 1_500_000.0,
    "ufs_ativas": 3,
    "narrative": {
        "padrao_competitivo": "Empresa com forte atuação em TI.",
        "principais_clientes": "Ministério da Saúde, Prefeitura de SP.",
        "setores_foco": "Tecnologia da Informação.",
        "pontos_atencao": "Alta concentração em cliente único.",
    },
    "orgaos_top": [
        {"orgao_nome": "Ministério da Saúde", "uf": "DF", "total_contratos": 3, "valor_total": 900_000.0},
        {"orgao_nome": "Prefeitura de SP", "uf": "SP", "total_contratos": 2, "valor_total": 600_000.0},
    ],
    "evolucao_temporal": [
        {"mes": "2025-01", "total_contratos": 2, "valor_total": 500_000.0},
        {"mes": "2025-02", "total_contratos": 3, "valor_total": 1_000_000.0},
    ],
    "objetos_top": [
        {"objeto": "Fornecimento de equipamentos de TI", "frequencia": 3, "valor_medio": 300_000.0},
        {"objeto": "Licença de software", "frequencia": 2, "valor_medio": 150_000.0},
    ],
    "uf_breakdown": {
        "DF": {"total_contratos": 3, "valor_total": 900_000.0},
        "SP": {"total_contratos": 2, "valor_total": 600_000.0},
    },
    "esfera_breakdown": {"F": 3, "M": 2},
    "contratos_recentes": [
        {
            "numero_controle": "CTRL-001",
            "orgao_nome": "Ministério da Saúde",
            "uf": "DF",
            "valor_global": 300_000.0,
            "data_assinatura": "2025-01-15",
            "objeto": "Fornecimento de servidores de alto desempenho para uso em ambiente de produção.",
        },
        {
            "numero_controle": "CTRL-002",
            "orgao_nome": "Prefeitura de SP",
            "uf": "SP",
            "valor_global": 200_000.0,
            "data_assinatura": "2025-02-20",
            "objeto": "Licença de software de gestão pública.",
        },
    ],
}


# ---------------------------------------------------------------------------
# Tests: generate_cnpj_report
# ---------------------------------------------------------------------------

class TestGenerateCnpjReport:
    """Tests for the PDF generator function."""

    def test_valid_data_returns_bytesio_with_pdf_magic_bytes(self):
        """PDF is generated correctly from complete data."""
        from pdf_generator_intel_report import generate_cnpj_report

        result = generate_cnpj_report(MINIMAL_DATA)

        assert isinstance(result, BytesIO)
        content = result.getvalue()
        assert len(content) > 0, "PDF must not be empty"
        assert content[:4] == b"%PDF", f"PDF must start with %PDF magic bytes, got {content[:4]!r}"

    def test_pdf_contains_reportlab_marker(self):
        """Generated bytes contain ReportLab marker (sanity check)."""
        from pdf_generator_intel_report import generate_cnpj_report

        result = generate_cnpj_report(MINIMAL_DATA)
        content = result.getvalue()
        # ReportLab always writes the PDF header comment
        assert b"%PDF-" in content

    def test_empty_dict_raises_value_error(self):
        """Empty dict raises ValueError."""
        from pdf_generator_intel_report import generate_cnpj_report

        with pytest.raises(ValueError):
            generate_cnpj_report({})

    def test_none_raises_value_error(self):
        """None input raises ValueError."""
        from pdf_generator_intel_report import generate_cnpj_report

        with pytest.raises(ValueError):
            generate_cnpj_report(None)  # type: ignore[arg-type]

    def test_minimal_data_without_optional_sections(self):
        """PDF generated even when optional sections (narrative, orgaos, etc.) are absent."""
        from pdf_generator_intel_report import generate_cnpj_report

        sparse = {
            "cnpj": "99.888.777/0001-00",
            "fornecedor_nome": "Empresa Vazia LTDA",
            "total_contratos": 0,
            "valor_total": 0.0,
        }
        result = generate_cnpj_report(sparse)
        content = result.getvalue()
        assert content[:4] == b"%PDF"
        assert len(content) > 500

    def test_no_narrative_field_uses_deterministic_fallback(self):
        """When 'narrative' key is missing, PDF is still generated via deterministic fallback."""
        from pdf_generator_intel_report import generate_cnpj_report

        data_no_narrative = {k: v for k, v in MINIMAL_DATA.items() if k != "narrative"}
        result = generate_cnpj_report(data_no_narrative)
        content = result.getvalue()
        assert content[:4] == b"%PDF"

    def test_bytesio_seeked_to_start(self):
        """Returned BytesIO is positioned at the start (tell() == 0)."""
        from pdf_generator_intel_report import generate_cnpj_report

        result = generate_cnpj_report(MINIMAL_DATA)
        assert result.tell() == 0


# ---------------------------------------------------------------------------
# Tests: LLM fallback path in the PDF pipeline
# ---------------------------------------------------------------------------

class TestGenerateCnpjReportLlmFallback:
    """Ensure PDF generation survives LLM failures."""

    def test_llm_exception_does_not_break_pdf(self):
        """If generate_cnpj_narrative raises an Exception, PDF is still generated."""
        from pdf_generator_intel_report import generate_cnpj_report

        # Build data without a 'narrative' key — simulating caller that would
        # normally inject the narrative from LLM. Even without narrative, the
        # PDF generator must not crash.
        data = {**MINIMAL_DATA}
        data.pop("narrative", None)

        result = generate_cnpj_report(data)
        content = result.getvalue()
        assert content[:4] == b"%PDF", "PDF must still be valid when narrative is absent"

    def test_generate_cnpj_narrative_falls_back_on_openai_exception(self):
        """generate_cnpj_narrative returns deterministic fallback when OpenAI raises."""
        from llm import generate_cnpj_narrative

        with patch("llm.OpenAI") as mock_openai_cls:
            mock_client = MagicMock()
            mock_openai_cls.return_value = mock_client
            mock_client.chat.completions.create.side_effect = Exception("API unavailable")

            # Ensure OPENAI_API_KEY is set so we reach the OpenAI call
            with patch.dict("os.environ", {"OPENAI_API_KEY": "test-key"}):
                result = generate_cnpj_narrative(MINIMAL_DATA)

        _assert_narrative_structure(result)

    def test_generate_cnpj_narrative_falls_back_when_no_api_key(self):
        """generate_cnpj_narrative returns deterministic fallback when API key is absent."""
        from llm import generate_cnpj_narrative

        with patch.dict("os.environ", {}, clear=True):
            # Remove OPENAI_API_KEY if present
            import os
            env_without_key = {k: v for k, v in os.environ.items() if k != "OPENAI_API_KEY"}
            with patch.dict("os.environ", env_without_key, clear=True):
                result = generate_cnpj_narrative(MINIMAL_DATA)

        _assert_narrative_structure(result)


# ---------------------------------------------------------------------------
# Tests: generate_cnpj_narrative
# ---------------------------------------------------------------------------

class TestGenerateCnpjNarrative:
    """Tests for the LLM narrative generation function."""

    def test_fallback_returns_all_required_keys(self):
        """Deterministic fallback returns dict with all 4 required keys."""
        from llm import _generate_cnpj_narrative_fallback

        result = _generate_cnpj_narrative_fallback(MINIMAL_DATA)
        _assert_narrative_structure(result)

    def test_fallback_with_empty_data(self):
        """Deterministic fallback handles empty data dict gracefully."""
        from llm import _generate_cnpj_narrative_fallback

        result = _generate_cnpj_narrative_fallback({})
        _assert_narrative_structure(result)
        assert result["padrao_competitivo"]  # must have some text

    def test_fallback_includes_total_contratos(self):
        """Fallback text mentions the total contracts count."""
        from llm import _generate_cnpj_narrative_fallback

        result = _generate_cnpj_narrative_fallback(MINIMAL_DATA)
        assert "5" in result["padrao_competitivo"]

    def test_llm_path_happy(self):
        """LLM path parses JSON response correctly when OpenAI returns valid JSON."""
        from llm import _generate_cnpj_narrative_llm

        fake_json = {
            "padrao_competitivo": "Padrão X",
            "principais_clientes": "Cliente A",
            "setores_foco": "TI",
            "pontos_atencao": "Atenção Y",
        }
        import json as _json

        mock_choice = MagicMock()
        mock_choice.message.content = _json.dumps(fake_json)

        mock_response = MagicMock()
        mock_response.choices = [mock_choice]

        with patch("llm.OpenAI") as mock_openai_cls:
            # mock_openai_cls() returns the mock client instance
            mock_openai_cls.return_value.chat.completions.create.return_value = mock_response

            with patch.dict("os.environ", {"OPENAI_API_KEY": "test-key"}):
                result = _generate_cnpj_narrative_llm(MINIMAL_DATA)

        assert result["padrao_competitivo"] == "Padrão X"
        assert result["principais_clientes"] == "Cliente A"
        assert result["setores_foco"] == "TI"
        assert result["pontos_atencao"] == "Atenção Y"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _assert_narrative_structure(result: dict) -> None:
    """Assert narrative dict has all 4 required string keys."""
    assert isinstance(result, dict), f"Expected dict, got {type(result)}"
    for key in ("padrao_competitivo", "principais_clientes", "setores_foco", "pontos_atencao"):
        assert key in result, f"Missing key: {key}"
        assert isinstance(result[key], str), f"Key {key} must be str, got {type(result[key])}"
