"""tests/test_subcontract_report_pdf.py — SUBINTEL-033: PDF generator tests.

Tests:
  1. Valid data → valid PDF (%PDF magic bytes)
  2. Empty entity_key → ValueError
  3. Invalid entity_key format → ValueError
  4. Minimal RPC data → PDF still generated
  5. Generated PDF has expected sections
  6. BytesIO seeked to start
"""

from __future__ import annotations

import pytest
from io import BytesIO
from unittest.mock import MagicMock


# ---------------------------------------------------------------------------
# Mock data: subcontract_intel RPC response
# ---------------------------------------------------------------------------

MOCK_RPC_DATA = {
    "entity_type": "cnpj",
    "entity_key": "12345678000195",
    "window_months": 24,
    "partnership_score": [
        {
            "score": 65,
            "factors": {
                "total_contratos": 12,
                "total_orgaos": 5,
                "total_ufs": 3,
                "avg_ticket": 150000.0,
                "hhi_concentracao": 2100.5,
                "tendencia_recente": "crescendo",
                "fornecedor_nome": "Empresa Exemplo LTDA",
            },
            "similar_suppliers": [
                {
                    "cnpj": "98765432000100",
                    "nome": "Concorrente A Ltda",
                    "contratos": 8,
                    "ufs": 4,
                },
            ],
            "recommended_actions": [
                {"action": "Abordar para parceria em SP, RJ", "priority": "alta"},
                {"action": "Avaliar carteira de orgaos em MG", "priority": "media"},
            ],
        },
    ],
    "regional_dependency": [
        {
            "uf_sigla": "SP",
            "dependency_index": 55.0,
            "contract_count": 7,
            "top_orgaos": [
                {"orgao_nome": "Governo do Estado de SP", "orgao_cnpj": "XX", "contratos": 4},
            ],
            "expansion_potential": "alta_dependencia",
        },
        {
            "uf_sigla": "RJ",
            "dependency_index": 25.0,
            "contract_count": 3,
            "top_orgaos": [],
            "expansion_potential": "diversificando",
        },
        {
            "uf_sigla": "MG",
            "dependency_index": 10.0,
            "contract_count": 2,
            "top_orgaos": [],
            "expansion_potential": "baixa_presenca",
        },
    ],
    "benchmark": [
        {
            "metric_name": "Total de Contratos",
            "competitor_value": 12.0,
            "sector_p25": 3.0,
            "sector_p50": 7.0,
            "sector_p75": 15.0,
            "competitor_percentile": 60,
            "interpretation": "Na media do setor",
        },
    ],
    "supplier_network": [
        {
            "source_cnpj": "12345678000195",
            "source_name": "Empresa Exemplo LTDA",
            "target_cnpj": "99887766000122",
            "target_name": "Potencial Parceiro Ltda",
            "weight": 5,
            "shared_orgaos": [
                {"orgao_nome": "Ministerio da Saude", "count": 3},
            ],
        },
    ],
}


def _make_mock_db(rpc_data: dict | None = None) -> MagicMock:
    """Create a mock supabase client that returns rpc_data from subcontract_intel."""
    db = MagicMock()
    rpc_chain = MagicMock()
    rpc_chain.execute.return_value = MagicMock(data=[rpc_data or MOCK_RPC_DATA])
    db.rpc.return_value = rpc_chain
    return db


# ---------------------------------------------------------------------------
# Tests: generate_subcontract_report
# ---------------------------------------------------------------------------


class TestGenerateSubcontractReport:
    """Tests for the subcontract report PDF generator."""

    def test_valid_cnpj_returns_bytesio_with_pdf_magic_bytes(self):
        """PDF is generated correctly from valid CNPJ data."""
        from pdf_generator_subcontract_report import generate_subcontract_report

        db = _make_mock_db()
        result = generate_subcontract_report(db=db, entity_key="12345678000195")

        assert isinstance(result, BytesIO)
        content = result.getvalue()
        assert len(content) > 0, "PDF must not be empty"
        assert content[:4] == b"%PDF", f"PDF must start with %PDF magic bytes, got {content[:4]!r}"

    def test_pdf_contains_reportlab_marker(self):
        """Generated bytes contain ReportLab marker."""
        from pdf_generator_subcontract_report import generate_subcontract_report

        db = _make_mock_db()
        result = generate_subcontract_report(db=db, entity_key="12345678000195")
        content = result.getvalue()
        assert b"%PDF-" in content

    def test_empty_entity_key_raises_value_error(self):
        """Empty entity_key raises ValueError."""
        from pdf_generator_subcontract_report import generate_subcontract_report

        db = _make_mock_db()
        with pytest.raises(ValueError):
            generate_subcontract_report(db=db, entity_key="")

    def test_whitespace_entity_key_raises_value_error(self):
        """Whitespace-only entity_key raises ValueError."""
        from pdf_generator_subcontract_report import generate_subcontract_report

        db = _make_mock_db()
        with pytest.raises(ValueError):
            generate_subcontract_report(db=db, entity_key="   ")

    def test_invalid_format_raises_value_error(self):
        """Invalid entity_key format (not CNPJ, not sector:UF) raises ValueError."""
        from pdf_generator_subcontract_report import generate_subcontract_report

        db = _make_mock_db()
        with pytest.raises(ValueError):
            generate_subcontract_report(db=db, entity_key="invalid_format")

    def test_minimal_data_still_generates_pdf(self):
        """Even with minimal data, PDF is generated."""
        from pdf_generator_subcontract_report import generate_subcontract_report

        minimal = {
            "entity_type": "cnpj",
            "entity_key": "12345678000195",
            "window_months": 24,
            "partnership_score": [],
            "regional_dependency": [],
            "benchmark": [],
            "supplier_network": [],
        }
        db = _make_mock_db(rpc_data=minimal)
        result = generate_subcontract_report(db=db, entity_key="12345678000195")
        content = result.getvalue()
        assert content[:4] == b"%PDF"
        assert len(content) > 500

    def test_bytesio_seeked_to_start(self):
        """Returned BytesIO is positioned at start."""
        from pdf_generator_subcontract_report import generate_subcontract_report

        db = _make_mock_db()
        result = generate_subcontract_report(db=db, entity_key="12345678000195")
        assert result.tell() == 0

    def test_rpc_call_uses_correct_parameters(self):
        """RPC is called with correct parameters."""
        from pdf_generator_subcontract_report import generate_subcontract_report

        db = MagicMock()
        rpc_chain = MagicMock()
        rpc_chain.execute.return_value = MagicMock(data=[MOCK_RPC_DATA])
        db.rpc.return_value = rpc_chain

        generate_subcontract_report(db=db, entity_key="12345678000195")

        db.rpc.assert_called_once_with(
            "subcontract_intel",
            {"p_entity_key": "12345678000195", "p_window_months": 24},
        )

    def test_rpc_error_raises_value_error(self):
        """When RPC returns no data, ValueError is raised."""
        from pdf_generator_subcontract_report import generate_subcontract_report

        db = MagicMock()
        rpc_chain = MagicMock()
        rpc_chain.execute.return_value = MagicMock(data=None)
        db.rpc.return_value = rpc_chain

        with pytest.raises(ValueError):
            generate_subcontract_report(db=db, entity_key="12345678000195")
