// AUTO-GENERATED by scripts/seo/uniqueness_audit.py — do not edit by hand.
// SEO-P0-003 (#989). To regenerate run:
//   python scripts/seo/uniqueness_audit.py --sitemap <url> \
//     --output docs/seo/audits/uniqueness-<yyyy-mm>.csv \
//     --emit-noindex-lib frontend/lib/seo/noindex-slugs.ts
//
// Format of each entry: '<family>:<path>' — matches the key returned by
// `noindexKey(family, path)` in `lib/seo/noindex.ts`.
//
// NOTE — initial commit ships with an empty set (no slugs blocked yet). The
// first real audit run is performed out-of-band against staging and the
// resulting list is committed in a follow-up PR. `noindex.ts` already gates
// `metadata.robots.index` against this set, so populating the list elsewhere
// flips noindex on without further code changes.

export const NOINDEX_SLUGS: ReadonlySet<string> = new Set([
  // Empty by default — populated by audit script output.
]);
