"""PT-BR stopwords list for deduplication tokenization.

Provides a comprehensive frozenset of Portuguese stopwords (NLTK-sourced,
hardcoded — no NLTK dependency) plus procurement-specific terms that carry
no semantic weight for Jaccard similarity comparisons.

Usage:
    from filter.stopwords import PT_BR_STOPWORDS

    tokens = [t for t in texto.split() if t not in PT_BR_STOPWORDS]

All words are stored in NFD-normalized form (without combining marks /
accents) so that "contratacao" and "contratacao" both hit the stopword check.
The caller is responsible for NFD normalizing the input text before comparing.
"""

# GAP-010: Extracted from DeduplicationEngine._FUZZY_STOPWORDS (inline ~30 words)
# to a dedicated module. Now 227 words: 200 unique NLTK PT-BR stopwords
# (NFD-normalized, originally 207 accented) + 27 procurement-specific terms.
#
# Words are stored WITHOUT accents (NFD-normalized form) so the same set works
# regardless of whether the input text has been accent-stripped or not.

PT_BR_STOPWORDS: frozenset[str] = frozenset({
    "a",
    "administrativo",
    "ao",
    "aos",
    "aquela",
    "aquelas",
    "aquele",
    "aqueles",
    "aquilo",
    "aquisicao",
    "as",
    "ate",
    "com",
    "como",
    "competitivo",
    "concorrencia",
    "concurso",
    "contratacao",
    "convite",
    "da",
    "das",
    "de",
    "dela",
    "delas",
    "dele",
    "deles",
    "depois",
    "dialogo",
    "disputa",
    "do",
    "dos",
    "e",
    "edital",
    "ela",
    "elas",
    "ele",
    "eles",
    "eletronica",
    "eletronico",
    "em",
    "entre",
    "era",
    "eram",
    "eramos",
    "essa",
    "essas",
    "esse",
    "esses",
    "esta",
    "estadual",
    "estamos",
    "estao",
    "estar",
    "estas",
    "estava",
    "estavam",
    "estavamos",
    "este",
    "esteja",
    "estejam",
    "estejamos",
    "estes",
    "esteve",
    "estive",
    "estivemos",
    "estiver",
    "estivera",
    "estiveram",
    "estiveramos",
    "estiverem",
    "estivermos",
    "estivesse",
    "estivessem",
    "estivessemos",
    "estou",
    "eu",
    "federal",
    "foi",
    "fomos",
    "for",
    "fora",
    "foram",
    "foramos",
    "forem",
    "formos",
    "fosse",
    "fossem",
    "fossemos",
    "fui",
    "ha",
    "habilitacao",
    "haja",
    "hajam",
    "hajamos",
    "hao",
    "havemos",
    "haver",
    "hei",
    "houve",
    "houvemos",
    "houver",
    "houvera",
    "houveram",
    "houveramos",
    "houverao",
    "houverei",
    "houverem",
    "houveremos",
    "houveria",
    "houveriam",
    "houveriamos",
    "houvermos",
    "houvesse",
    "houvessem",
    "houvessemos",
    "isso",
    "isto",
    "ja",
    "leilao",
    "lhe",
    "lhes",
    "licitacao",
    "mais",
    "mas",
    "me",
    "mesmo",
    "meu",
    "meus",
    "minha",
    "minhas",
    "modalidade",
    "muito",
    "municipal",
    "na",
    "nao",
    "nas",
    "nem",
    "no",
    "nos",
    "nossa",
    "nossas",
    "nosso",
    "nossos",
    "num",
    "numa",
    "o",
    "os",
    "ou",
    "para",
    "participacao",
    "pela",
    "pelas",
    "pelo",
    "pelos",
    "por",
    "precos",
    "pregao",
    "presencial",
    "processo",
    "propostas",
    "publica",
    "qual",
    "quando",
    "que",
    "quem",
    "sao",
    "se",
    "seja",
    "sejam",
    "sejamos",
    "sem",
    "ser",
    "sera",
    "serao",
    "serei",
    "seremos",
    "seria",
    "seriam",
    "seriamos",
    "seu",
    "seus",
    "so",
    "somos",
    "sou",
    "sua",
    "suas",
    "tambem",
    "te",
    "tem",
    "temos",
    "tenha",
    "tenham",
    "tenhamos",
    "tenho",
    "tera",
    "terao",
    "terei",
    "teremos",
    "teria",
    "teriam",
    "teriamos",
    "teu",
    "teus",
    "teve",
    "tinha",
    "tinham",
    "tinhamos",
    "tive",
    "tivemos",
    "tiver",
    "tivera",
    "tiveram",
    "tiveramos",
    "tiverem",
    "tivermos",
    "tivesse",
    "tivessem",
    "tivessemos",
    "tomada",
    "tu",
    "tua",
    "tuas",
    "um",
    "uma",
    "voce",
    "voces",
    "vos",
})


def is_stopword(word: str) -> bool:
    """Check if a word (already NFD-normalized, lowercase) is a stopword."""
    return word in PT_BR_STOPWORDS
