#!/usr/bin/env python3
"""DATA-CNAE-001 (AC13): CNAE coverage report.

Produces ``docs/reports/cnae-coverage-{YYYY-MM-DD}.md`` summarising:
    * Total active rows in ``cnae_setor_mapping``
    * Distribution by ``setor_id`` (pivots which sectors are over- or
      under-represented)
    * CNAEs in the legacy snapshot that are NOT in the DB (data drift —
      means the seed ran but a row was deleted without admin
      intent, OR a new admin-edited row hasn't synced yet).
    * CNAEs in the DB that are NOT in the legacy snapshot (admin-added
      rows since the migration).
    * Audit trail summary for the last 30 days (mutation counts by
      action / actor).

The official IBGE CNAE master list is not available offline.  When
the list IS provided (CSV at ``data/ibge_cnae_master.csv`` with a
``codigo_4d`` column) the report cross-references it: it logs IBGE
codes missing from the DB ("uncovered") and DB codes that are no
longer in IBGE ("retired by IBGE — consider soft-delete").

Usage:
    python scripts/cnae_coverage_report.py

Reads SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY from the env (matching
the backend's supabase_client).  Exits 0 on success, 1 on failure.
"""

from __future__ import annotations

import csv
import os
import sys
from collections import Counter
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
REPORTS_DIR = REPO_ROOT / "docs" / "reports"
LEGACY_MODULE = REPO_ROOT / "backend" / "utils" / "cnae_mapping.py"
IBGE_MASTER_PATH = REPO_ROOT / "data" / "ibge_cnae_master.csv"


def _load_legacy_dict() -> dict[str, str]:
    """Pure-Python parse of _LEGACY_CNAE_TO_SETOR (no DB import)."""
    source = LEGACY_MODULE.read_text(encoding="utf-8")
    namespace: dict[str, object] = {}
    exec(compile(source, str(LEGACY_MODULE), "exec"), namespace)  # noqa: S102
    legacy = namespace.get("_LEGACY_CNAE_TO_SETOR")
    if not isinstance(legacy, dict):
        raise SystemExit("_LEGACY_CNAE_TO_SETOR not found in cnae_mapping.py")
    return legacy


def _load_ibge_master() -> set[str]:
    """Load the IBGE master CNAE list if shipped, else empty set."""
    if not IBGE_MASTER_PATH.exists():
        return set()
    out: set[str] = set()
    with IBGE_MASTER_PATH.open(encoding="utf-8-sig", newline="") as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            code = (row.get("codigo_4d") or row.get("cnae") or "").strip()
            if code and code.isdigit() and len(code) == 4:
                out.add(code)
    return out


def _query_db_state() -> tuple[list[dict], list[dict]]:
    """Pull all rows from cnae_setor_mapping + last-30d audit entries.

    Returns ([mappings], [audit_rows]).  Empty lists if Supabase
    creds are missing — the report still renders against the
    legacy-only baseline.
    """
    url = os.getenv("SUPABASE_URL")
    key = os.getenv("SUPABASE_SERVICE_ROLE_KEY") or os.getenv("SUPABASE_KEY")
    if not url or not key:
        print("WARN: SUPABASE_URL/KEY not set — skipping DB section.")
        return [], []
    try:
        from supabase import create_client  # type: ignore
    except Exception:
        print("WARN: supabase python lib unavailable — skipping DB section.")
        return [], []

    client = create_client(url, key)
    mappings = (
        client.table("cnae_setor_mapping")
        .select("*")
        .order("cnae_code")
        .limit(10_000)
        .execute()
    )
    cutoff = (datetime.now(timezone.utc) - timedelta(days=30)).isoformat()
    audit = (
        client.table("cnae_mapping_audit_log")
        .select("action, actor_email, created_at, cnae_code")
        .gte("created_at", cutoff)
        .order("created_at", desc=True)
        .limit(10_000)
        .execute()
    )
    return list(mappings.data or []), list(audit.data or [])


def _render_markdown(
    *,
    mappings: list[dict],
    audit: list[dict],
    legacy: dict[str, str],
    ibge: set[str],
) -> str:
    today = date.today().isoformat()
    active = [m for m in mappings if m.get("is_active")]
    inactive = [m for m in mappings if not m.get("is_active")]
    by_setor = Counter(m["setor_id"] for m in active)

    legacy_codes = set(legacy)
    db_codes = {m["cnae_code"] for m in active}
    in_legacy_not_db = sorted(legacy_codes - db_codes)
    in_db_not_legacy = sorted(db_codes - legacy_codes)

    lines = [
        f"# CNAE Coverage Report — {today}",
        "",
        "Generated by `scripts/cnae_coverage_report.py` (DATA-CNAE-001 AC13).",
        "",
        "## Snapshot",
        "",
        f"- Active mappings in DB: **{len(active)}**",
        f"- Inactive (soft-deleted) mappings: **{len(inactive)}**",
        f"- Legacy snapshot (`_LEGACY_CNAE_TO_SETOR`): **{len(legacy)}** codes",
    ]
    if ibge:
        coverage = (len(db_codes & ibge) / len(ibge)) * 100 if ibge else 0
        lines.append(
            f"- IBGE master codes loaded: **{len(ibge)}** "
            f"({coverage:.1f}% covered by active rows)"
        )

    lines.extend(
        [
            "",
            "## Distribution by sector",
            "",
            "| setor_id | active rows |",
            "|----------|------------:|",
        ]
    )
    for setor_id, count in sorted(by_setor.items(), key=lambda kv: (-kv[1], kv[0])):
        lines.append(f"| {setor_id} | {count} |")

    lines.extend(
        [
            "",
            "## Drift vs legacy snapshot",
            "",
            f"- In legacy but missing from DB ({len(in_legacy_not_db)}): "
            + (", ".join(in_legacy_not_db) or "_(none — clean)_"),
            "",
            f"- In DB but absent from legacy ({len(in_db_not_legacy)}): "
            + (", ".join(in_db_not_legacy) or "_(none — clean)_"),
        ]
    )

    if ibge:
        uncovered = sorted(ibge - db_codes)
        retired = sorted(db_codes - ibge)
        lines.extend(
            [
                "",
                "## IBGE cross-reference",
                "",
                f"- IBGE codes uncovered (route to `geral` fallback) "
                f"({len(uncovered)}): "
                + (", ".join(uncovered[:50]) or "_(none)_")
                + ("…" if len(uncovered) > 50 else ""),
                "",
                f"- DB codes no longer in IBGE (review for soft-delete) "
                f"({len(retired)}): "
                + (", ".join(retired) or "_(none)_"),
            ]
        )

    if audit:
        by_action = Counter(a["action"] for a in audit)
        by_actor = Counter(a.get("actor_email") or "(system)" for a in audit)
        lines.extend(
            [
                "",
                "## Last 30 days — audit summary",
                "",
                f"- Total mutations: **{len(audit)}**",
                "",
                "| action | count |",
                "|--------|------:|",
            ]
        )
        for action_name, count in sorted(by_action.items()):
            lines.append(f"| {action_name} | {count} |")
        lines.extend(["", "| actor | mutations |", "|-------|----------:|"])
        for actor, count in sorted(by_actor.items(), key=lambda kv: (-kv[1], kv[0])):
            lines.append(f"| {actor} | {count} |")

    lines.append("")
    return "\n".join(lines)


def main() -> int:
    legacy = _load_legacy_dict()
    ibge = _load_ibge_master()
    mappings, audit = _query_db_state()
    md = _render_markdown(mappings=mappings, audit=audit, legacy=legacy, ibge=ibge)

    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    target = REPORTS_DIR / f"cnae-coverage-{date.today().isoformat()}.md"
    target.write_text(md, encoding="utf-8")
    print(f"Wrote {target}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
