#!/usr/bin/env python3
"""DATA-CNAE-001 (AC4): Generate the cnae_setor_mapping seed migration.

Reads the legacy in-memory mapping from
``backend/utils/cnae_mapping.py::_LEGACY_CNAE_TO_SETOR`` and emits an
idempotent ``INSERT ... ON CONFLICT DO UPDATE`` block.  The output is
written to ``supabase/migrations/20260428101000_seed_cnae_mapping.sql``.

Idempotency contract:
    * Rerunning the script produces a byte-identical SQL file (the
      legacy dict iteration order is preserved by Python 3.7+).
    * Re-applying the migration is a no-op when rows already match
      because the upsert clause only touches columns when the source
      data differs.
    * Setting ``confidence = 1.0`` and ``is_active = TRUE`` is
      intentional: every row in the legacy dict is canonical and the
      AC15 snapshot regression test compares against ``is_active=TRUE``.

Usage:
    python scripts/generate_cnae_seed.py            # write the .sql
    python scripts/generate_cnae_seed.py --check    # exit 1 if drift

The ``--check`` flag is the CI hook: run it in the migration-gate
workflow to catch drift between the legacy dict and the seed file.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Iterable

# Resolve project root from this script's location so the script works
# regardless of cwd.  scripts/ is at the repo root.
REPO_ROOT = Path(__file__).resolve().parent.parent
SEED_PATH = (
    REPO_ROOT
    / "supabase"
    / "migrations"
    / "20260428101000_seed_cnae_mapping.sql"
)
LEGACY_MODULE_PATH = REPO_ROOT / "backend" / "utils" / "cnae_mapping.py"

HEADER = """-- DATA-CNAE-001 (AC4): Seed cnae_setor_mapping from legacy hardcoded
-- mapping in backend/utils/cnae_mapping.py::_LEGACY_CNAE_TO_SETOR.
--
-- AUTOGENERATED BY scripts/generate_cnae_seed.py — DO NOT EDIT BY HAND.
-- To refresh, edit _LEGACY_CNAE_TO_SETOR in cnae_mapping.py then run:
--     python scripts/generate_cnae_seed.py
--
-- Idempotency: ON CONFLICT DO UPDATE preserves existing audit metadata
-- (updated_by, updated_at) when the seed value already matches.

INSERT INTO public.cnae_setor_mapping (cnae_code, setor_id, confidence, is_active, notes)
VALUES
"""

FOOTER = (
    "ON CONFLICT (cnae_code) DO UPDATE\n"
    "    SET setor_id   = EXCLUDED.setor_id,\n"
    "        confidence = EXCLUDED.confidence,\n"
    "        is_active  = EXCLUDED.is_active,\n"
    "        notes      = EXCLUDED.notes,\n"
    "        updated_at = now()\n"
    "    WHERE\n"
    "        public.cnae_setor_mapping.setor_id   IS DISTINCT FROM EXCLUDED.setor_id\n"
    "     OR public.cnae_setor_mapping.confidence IS DISTINCT FROM EXCLUDED.confidence\n"
    "     OR public.cnae_setor_mapping.is_active  IS DISTINCT FROM EXCLUDED.is_active\n"
    "     OR public.cnae_setor_mapping.notes      IS DISTINCT FROM EXCLUDED.notes;\n"
)


def _load_legacy_mapping() -> dict[str, str]:
    """Import _LEGACY_CNAE_TO_SETOR without invoking module side-effects.

    We don't want to import ``backend.utils.cnae_mapping`` directly
    because that triggers DB-aware code paths added by DATA-CNAE-001.
    Instead, parse the source file in isolation: the legacy dict is a
    pure-Python literal we can ``exec`` safely in a sandboxed
    namespace.
    """
    source = LEGACY_MODULE_PATH.read_text(encoding="utf-8")
    namespace: dict[str, object] = {}
    exec(  # noqa: S102 — controlled source, this is the canonical seed source
        compile(source, str(LEGACY_MODULE_PATH), "exec"),
        namespace,
    )
    legacy = namespace.get("_LEGACY_CNAE_TO_SETOR")
    if not isinstance(legacy, dict):
        raise SystemExit(
            "scripts/generate_cnae_seed.py: _LEGACY_CNAE_TO_SETOR not "
            "found or not a dict in backend/utils/cnae_mapping.py — "
            "did the refactor land?"
        )
    return legacy


def _quote(text: str) -> str:
    """Postgres single-quoted string literal with apostrophe escape."""
    return "'" + text.replace("'", "''") + "'"


def _render_rows(mapping: dict[str, str]) -> Iterable[str]:
    """Yield one VALUES row per CNAE, sorted for deterministic diffs."""
    for cnae in sorted(mapping):
        setor = mapping[cnae]
        yield (
            f"    ({_quote(cnae)}, {_quote(setor)}, 1.0, TRUE, "
            f"'Seeded from legacy cnae_mapping.py 2026-04-28')"
        )


def _build_sql(mapping: dict[str, str]) -> str:
    rows = list(_render_rows(mapping))
    if not rows:
        raise SystemExit("Refusing to emit a seed with zero rows.")
    body = ",\n".join(rows) + "\n"
    return HEADER + body + FOOTER


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if the existing seed file does not match the dict.",
    )
    args = parser.parse_args()

    mapping = _load_legacy_mapping()
    sql = _build_sql(mapping)

    if args.check:
        if not SEED_PATH.exists():
            print(f"FAIL: {SEED_PATH} does not exist; run without --check")
            return 1
        on_disk = SEED_PATH.read_text(encoding="utf-8")
        if on_disk != sql:
            print(
                f"FAIL: {SEED_PATH} drifted from "
                "_LEGACY_CNAE_TO_SETOR; rerun the script."
            )
            return 1
        print(f"OK: {SEED_PATH} is in sync with the legacy dict.")
        return 0

    SEED_PATH.parent.mkdir(parents=True, exist_ok=True)
    SEED_PATH.write_text(sql, encoding="utf-8")
    print(f"Wrote {len(mapping)} rows to {SEED_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
