-- DATA-CNAE-001 (AC4): Seed cnae_setor_mapping from legacy hardcoded
-- mapping in backend/utils/cnae_mapping.py::_LEGACY_CNAE_TO_SETOR.
--
-- AUTOGENERATED BY scripts/generate_cnae_seed.py — DO NOT EDIT BY HAND.
-- To refresh, edit _LEGACY_CNAE_TO_SETOR in cnae_mapping.py then run:
--     python scripts/generate_cnae_seed.py
--
-- Idempotency: ON CONFLICT DO UPDATE preserves existing audit metadata
-- (updated_by, updated_at) when the seed value already matches.

INSERT INTO public.cnae_setor_mapping (cnae_code, setor_id, confidence, is_active, notes)
VALUES
    ('1011', 'alimentos', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('1091', 'alimentos', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('1412', 'vestuario', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('1413', 'vestuario', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('1421', 'vestuario', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('1422', 'vestuario', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('2710', 'equipamentos', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('2759', 'equipamentos', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('2861', 'equipamentos', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('3250', 'saude', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('4120', 'engenharia', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('4211', 'engenharia', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('4212', 'engenharia', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('4213', 'engenharia', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('4221', 'engenharia', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('4222', 'engenharia', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('4223', 'engenharia', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('4291', 'engenharia', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('4292', 'engenharia', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('4299', 'engenharia', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('4311', 'engenharia', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('4312', 'engenharia', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('4313', 'engenharia', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('4319', 'engenharia', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('4321', 'engenharia', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('4322', 'engenharia', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('4329', 'engenharia', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('4391', 'engenharia', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('4399', 'engenharia', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('4639', 'alimentos', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('4644', 'saude', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('4645', 'saude', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('4711', 'alimentos', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('4781', 'vestuario', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('4921', 'transporte', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('4922', 'transporte', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('4924', 'transporte', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('4929', 'transporte', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('4930', 'transporte', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('6201', 'informatica', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('6202', 'informatica', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('6209', 'informatica', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('6311', 'informatica', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('6319', 'informatica', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('7111', 'engenharia', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('7112', 'engenharia', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('7119', 'engenharia', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('8011', 'vigilancia', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('8012', 'vigilancia', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('8121', 'servicos_prediais', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('8122', 'servicos_prediais', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('8129', 'servicos_prediais', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('8130', 'servicos_prediais', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('8411', 'engenharia', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('8412', 'engenharia', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('8413', 'engenharia', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('8610', 'saude', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('8621', 'saude', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28'),
    ('8630', 'saude', 1.0, TRUE, 'Seeded from legacy cnae_mapping.py 2026-04-28')
ON CONFLICT (cnae_code) DO UPDATE
    SET setor_id   = EXCLUDED.setor_id,
        confidence = EXCLUDED.confidence,
        is_active  = EXCLUDED.is_active,
        notes      = EXCLUDED.notes,
        updated_at = now()
    WHERE
        public.cnae_setor_mapping.setor_id   IS DISTINCT FROM EXCLUDED.setor_id
     OR public.cnae_setor_mapping.confidence IS DISTINCT FROM EXCLUDED.confidence
     OR public.cnae_setor_mapping.is_active  IS DISTINCT FROM EXCLUDED.is_active
     OR public.cnae_setor_mapping.notes      IS DISTINCT FROM EXCLUDED.notes;
